### ISSUE TITLE
Issues erstellen, Pull Requests nutzen

### ISSUE THREAD

**Issue by nipafx** [yddaPyo/Info-Klausur#11]
Bitte erstellt alle Issues für den ersten Block, sowie einen Meilenstein, dem ihr die Issues zuordnet.

Ihr commitet regelmäßig direkt auf `master` - statt dessen sollt ihr die Aufgaben auf Branches bearbeiten und dann Pull Requests öffnen.

**Comment by zvenon** [comment]
Okay. Danke.
Auch möglich mit meinem fork zu arbeiten, dann ein Pull Request zu öffnen und fork mit master branch compare?

**Comment by nipafx** [comment]
Abgehesen von Releases (die direkt auf `master` gemacht werden) solltet ihr niemals auf `master` arbeiten - auch nicht im Fork, denn das macht nur Probleme.

**Comment by nipafx** [comment]
Es fehlt zumindest noch das Issue zu Travis...

**Comment by nipafx** [comment]
Denkt daran vor Beginn der Arbeit am zweiten Block, Issues für jede Aufgabe zu erstellen und sie einem Meilenstein zuzuordnen.

**Comment by archdtd111** [comment]
Jawohl! Danke für die Erinnerung.

**Comment by nipafx** [comment]
Super, dann mach ich das mal zu.
