### ISSUE TITLE
integrate with Travis 

### ISSUE THREAD

**Issue by zvenon** [yddaPyo/Info-Klausur#21]

**Comment by nipafx** [comment]
Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @yddaPyo .

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen.

**Comment by yddaPyo** [comment]
Die Schritte sind ausgeführt, sodass Sie nun arbeiten können.
