### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by archdtd111** [yddaPyo/Info-Klausur#30]
Erstellen der Datei Network für die Verkehrssimulation.
Näheres im Olat. Hier der Link:
https://olat.vcrp.de/auth/RepositoryEntry/1676804160/CourseNode/95999652079122

**Comment by nipafx** [comment]
Die Issues scheinen sehr kleinteilig zu werden, d.h. es wird fast nicht möglich sein, nur eines davon zu bearbeiten. Bitte erstell ein Issue _je Top-Level-Bulletpoint_ (steht auch so im Olat). Außerdem sollen die Issues für sich alleine stehen, d.h. ohne OLAT verständlich sein. Deswegen bite die Beschreibung entsprechend füllen.
