### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by zvenon** [yddaPyo/Info-Klausur#7]

**Comment by zvenon** [comment]
Noch einiges zu machen an Aufgabe1. Derzeit hängt es am JAR und pom.xml. Sobald wir mal einen Schritt vorwärts kommen muss Aufgabe1 released werden.

**Comment by nipafx** [comment]
Sobald alle Issues im [ersten Meilenstein](https://github.com/yddaPyo/Info-Klausur/milestone/1) geschlossen sind, kann das Release gemacht werden. So geht's:

* `master` auschecken (wichtig: muss aktuell sein!)
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen:

![attach-binaries](https://user-images.githubusercontent.com/6537432/28945052-36db7a44-78a5-11e7-843c-892c9de473b8.png)

Dies ist die einzige Aktion, die _nicht_ über einen Pull Request sondern direkt auf `master` gelöst wird!

**Comment by nipafx** [comment]
Ausgezeichnet! :smiley:

**Comment by archdtd111** [comment]
Dankeschön :3
