### ISSUE TITLE
 JAR und pom.xml

### ISSUE THREAD

**Issue by zvenon** [yddaPyo/Info-Klausur#8]
WICHTIG!!! siehe Ordner Respository.

**Comment by nipafx** [comment]
Der aktuelle Stand des Repositories ist ein brauchbarer Anfang für einen erfolgreichen Maven Build. Allerdings gehören die Dateien und Ordner in `INFO` direkt in das Projektverzeichnis. Wenn ihr einen neuen Pull Request öffnet, in dem der Inhalt des `INFO` Ordners eine ebene hoch kopiert wird, können wir dann anfangen die fehlerhaften Details auszubessern.

**Comment by nipafx** [comment]
Nachdem #10 frühzeitig gemergt wurde, muss jetzt nachgebessert werden:

* Ordner `org.archdtd111.INFO` (in `src/main/kotlin`) und Inhalt können gelöscht werden
* Ordner `INFO` (in obersten Verzeichnis) und Inhalt können gelöscht werden

Danach könnte `mvn clean install` durchlaufen.
